### ISSUE TITLE
[Bug] Something is wrong with (&&, ...).

### ISSUE THREAD

**Issue by MoonWalker1997** [bowen-xu/PyNARS#16]
**Describe the bug**
Something is wrong with (&&, ...). A question cannot be directly raised.

**To Reproduce**
1. Just run the console (python Console.py in /pynars).
2. Type the following commands **`(&&, <(*, A, B) --> rel1>, <(*, B, C) --> rel2>, <A --> [pos]>, <C --> [pos]>)?`**
3. It will show **`Unknown error: (&&,<(*, A, B) --> rel1>,<(*, B, C) --> rel2>,<A --> [pos]>, <B --> [pos]>)? repr() takes 1 positional argument but 2 were given`**
4. But when I input the same sentence as a judgment, say **`(&&, <(*, A, B) --> rel1>, <(*, B, C) --> rel2>, <A --> [pos]>, <C --> [pos]>).`**, it will be fine.

**Expected behavior**
Inputing this command should not give errors.

**Screenshots**
<img width="986" alt="image" src="https://github.com/bowen-xu/PyNARS/assets/55757689/f401c4ff-3a90-441a-ac4c-1f5fc539f758">

**Environment (please complete the following information):**
 - OS: MacOS 13.4
 - Language: Python 3.9
 - PyNARS branch and report date: dev; Sep 13, 2023

**Comment by bowen-xu** [comment]
This is is because in the old version there was an argument for printing a sentence, while in the new version, that argument is removed, but some code which calls the function still passes the values to it.

https://github.com/bowen-xu/PyNARS/blob/5491942b8a95de5decab593e80d0b5e39416b50e/pynars/Narsese/_py/Sentence.py#L203-L204

https://github.com/bowen-xu/PyNARS/blob/5491942b8a95de5decab593e80d0b5e39416b50e/pynars/Narsese/_py/Sentence.py#L220-L221

The `is_input` should not be passed into `repr()`.

**Comment by bowen-xu** [comment]
@MoonWalker1997 Please update to the newest commit [9a970f0](https://github.com/bowen-xu/PyNARS/commit/9a970f0c02e9d912d614aaa020ab7b3ed18280b4) and see whether the bug is fixed.

**Comment by bowen-xu** [comment]
Bug fixed.
